SELECT '[1, 2, 3]'::tensor;
SELECT '[[1, 2], [3, 4]]'::tensor;
SELECT '[1.,2.,3.]'::tensor;
SELECT ' [ [ 1,  2    ] , [    3 , 4 ] ] '::tensor;
SELECT '[[[1.2345]]]'::tensor;
SELECT '[hello, 1]'::tensor;
SELECT '[NaN,1]'::tensor;
SELECT '[Infinity,1]'::tensor;
SELECT '[-Infinity,1]'::tensor;
SELECT '[1.5e38, -1.5e38]'::tensor;
SELECT '[1.5e+38,-1.5e+38]'::tensor;
SELECT '[1.5e-38,-1.5e-38]'::tensor;
SELECT '[4e38,1]'::tensor;
SELECT '[-4e38,1]'::tensor;
SELECT '[1e-46,1]'::tensor;
SELECT '[-1e-46,1]'::tensor;
SELECT '[1,2,3'::tensor;
SELECT '[1,2,3]9'::tensor;
SELECT '1,2,3'::tensor;
SELECT ''::tensor;
SELECT '['::tensor;
SELECT '[ '::tensor;
SELECT '[,'::tensor;
SELECT '[]'::tensor;
SELECT '[[],[]]'::tensor;
SELECT '[ ]'::tensor;
SELECT '[,]'::tensor;
SELECT '[1,]'::tensor;
SELECT '[1a]'::tensor;
SELECT '[1,,3]'::tensor;
SELECT '[1, ,3]'::tensor;
SELECT '[[], ]]'::tensor;
SELECT '[[1, 2], [3]]'::tensor;
SELECT '[[[1, 2], [3, 4]], [[1, 2], [3, 4, 5]]]'::tensor;
SELECT '[[[1, 2], [3, 4]], [[5, 6], [7, 8],]]'::tensor;
SELECT '[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]'::tensor;
